#!/usr/bin/env node

/**
 * Verification script for robots.txt and sitemap configuration
 * Run: node scripts/verify-robots.js
 * 
 * Checks:
 * - robots.txt exists in dist/
 * - Sitemap URL is valid
 * - Sitemap is accessible
 * - No hardcoded localhost URLs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const distPath = path.join(__dirname, '../dist');
const robotsPath = path.join(distPath, 'robots.txt');
const sitemapPath = path.join(distPath, 'sitemap.xml');

let hasErrors = false;

console.log('🔍 Verifying robots.txt and sitemap configuration...\n');

// Check 1: robots.txt exists
console.log('Check 1: robots.txt file exists');
if (fs.existsSync(robotsPath)) {
  console.log('  ✅ robots.txt found\n');
} else {
  console.log('  ❌ robots.txt NOT found in dist/\n');
  hasErrors = true;
}

// Check 2: robots.txt is not empty
console.log('Check 2: robots.txt content');
try {
  const robotsContent = fs.readFileSync(robotsPath, 'utf8');
  
  if (robotsContent.length === 0) {
    console.log('  ❌ robots.txt is empty\n');
    hasErrors = true;
  } else {
    console.log(`  ✅ robots.txt size: ${robotsContent.length} bytes\n`);
    
    // Check 3: Sitemap URL is valid
    console.log('Check 3: Sitemap URL format');
    const sitemapMatch = robotsContent.match(/Sitemap:\s*(.+)/i);
    
    if (sitemapMatch) {
      const sitemapUrl = sitemapMatch[1].trim();
      
      // Validate URL format
      try {
        const url = new URL(sitemapUrl);
        
        // Check for localhost or 127.0.0.1
        if (url.hostname === 'localhost' || url.hostname === '127.0.0.1' || url.hostname === '0.0.0.0') {
          console.log(`  ❌ Sitemap uses localhost: ${sitemapUrl}`);
          console.log('     This will break in production!\n');
          hasErrors = true;
        } else {
          console.log(`  ✅ Sitemap URL: ${sitemapUrl}\n`);
          
          // Check 4: Sitemap file exists
          console.log('Check 4: sitemap.xml file');
          if (fs.existsSync(sitemapPath)) {
            const sitemapSize = fs.statSync(sitemapPath).size;
            console.log(`  ✅ sitemap.xml found (${sitemapSize} bytes)\n`);
          } else {
            console.log('  ⚠️  sitemap.xml not found (might be generated by external service)\n');
          }
        }
      } catch (e) {
        console.log(`  ❌ Invalid Sitemap URL: ${sitemapUrl}`);
        console.log(`     Error: ${e.message}\n`);
        hasErrors = true;
      }
    } else {
      console.log('  ❌ No Sitemap URL found in robots.txt\n');
      hasErrors = true;
    }
    
    // Check 5: robots.txt syntax
    console.log('Check 5: robots.txt syntax');
    const hasUserAgent = /User-agent:/i.test(robotsContent);
    const hasDisallow = /Disallow:/i.test(robotsContent);
    
    if (hasUserAgent && hasDisallow) {
      console.log('  ✅ Valid robots.txt structure\n');
    } else {
      console.log('  ⚠️  Missing standard robots.txt directives\n');
    }
  }
} catch (error) {
  console.log(`  ❌ Error reading robots.txt: ${error.message}\n`);
  hasErrors = true;
}

// Final report
console.log('─'.repeat(50));
if (hasErrors) {
  console.log('❌ Verification FAILED');
  console.log('\nFix the issues above and rerun: npm run build && npm run verify-robots');
  process.exit(1);
} else {
  console.log('✅ All checks passed!');
  console.log('\nYour robots.txt is correctly configured for production.');
  process.exit(0);
}
